version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - backend

  backend:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_SERVER=backend
      - ME_CONFIG_MONGODB_PORT=27017

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mongo-data:
