version: '3.9'
services:
  webapp:
    container_name: webapp
    image: latest/webapp
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  mongodata:

networks:
  backend:
    interal: true
  frontend
