# Dockerfile.frontend

# FROM specifies the base image, here we are using an offical Nginx image. 
# Apline claims to make containers smaller and more efficient.
FROM nginx:alpine

# Copy static files from 'public' directory to Nginx web directory
COPY public /usr/share/nginx/html

# Container will listen on 80 which is the default HTTP port
EXPOSE 80
