version: '3.9'

services:
  ecommerce-app:
    container_name: webapp
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ecommerce-app
    networks:
      - frontend

volumes:
  mongodata:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
