version: '3.9'

services:
  web:
    build:
      context: . # directory of file
      dockerfile: Dockerfile.backend # filename used to build container
    container_name: web
    environment:
      MONGO_URL: mongodb://admin:pass@mongo:27017/shopping-cart?authSource=admin # configures mongoDB using credentials 'admin' and 'pass'
    ports:
      - "3000:3000" # the first 3000 is the port on host machine, enabling the app to be accessable though 'localhost:3000'
      # the second 3000 is the port of the backend container, specified in Dockerfile.backend
    depends_on:
      - mongo # waits for mongoDB to be ready before running the container
    networks:
      - backend # connects to backend network so it can interact with other services, such as mongoDB

  frontend:
    build:
      context: . # directory of file
      dockerfile: Dockerfile.frontend # filename used to build container
    container_name: frontend
    ports:
      - "8081:80" # maps frontend to port 8081 so the frontend can be accessable through 'localhost:8081'
      # 80 is the default port for HTTP linking the container to the frontend container, specified in Dockerfile.frontend
    networks:
      - backend # link backend for communication with other services.

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/localhost.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/localhost.key
    ports:
      - "443:443"
    depends_on:
      - frontend
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
  frontend:
