version: '3.9'

services:
  ecommerce-app:
    container_name: webapp
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - backend

volumes:
  mongodata:

networks:
  backend:
    driver: bridge
