version: '3.9'

services:
  web:
<<<<<<< HEAD
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: web
    environment:
      MONGO_URL: mongodb://admin:pass@mongo:27017/shopping-cart?authSource=admin
=======
    build: .
    container_name: web
>>>>>>> 98b21eb (added docker-compose)
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend

<<<<<<< HEAD
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8081:80"
    networks:
      - backend

=======
>>>>>>> 98b21eb (added docker-compose)
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8081:8081"
>>>>>>> 98b21eb (added docker-compose)
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
<<<<<<< HEAD
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/localhost.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/localhost.key
    ports:
      - "443:443"
    depends_on:
      - frontend
=======
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "443:443"
    depends_on:
      - web
>>>>>>> 98b21eb (added docker-compose)
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
<<<<<<< HEAD
  frontend:
=======
>>>>>>> 98b21eb (added docker-compose)
