apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - name: backend
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000  # Node port for the backend
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32001  # Node port for the frontend
